=== robe92/sp3/src/main/java/Xml/aftale.dtd
<!ELEMENT aftaler (aftale*)>
        <!ELEMENT aftale (info*)>
        <!ELEMENT info (cpr,date,time,hospital,afdeling,adresse)>
        <!ELEMENT cpr (#PCDATA)>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT hospital (#PCDATA)>
        <!ELEMENT adresse (#PCDATA)>
        <!ELEMENT afdeling (#PCDATA)>

=== robe92/sp3/src/main/java/Xml/aftale.XML
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE aftale SYSTEM "aftale.dtd">
<aftale>
    <info>
        <cpr></cpr>
        <date></date>
        <time></time>
        <hospital></hospital>
        <afdeling></afdeling>
        <adresse></adresse>
    </info>
</aftale>
